engines:
  bandit:
    exclude_paths:
      - "doc/source/conf.py"

exclude_paths:
  - 'tests/**'
  - 'sample_data/**.json'
  - 'Dockerfile'
  - 'pyramid_oereb/contrib/stats/scripts/**'
  - '.devcontainer/**'
