FROM openoereb-oereb-main
LABEL maintainer "info@camptocamp.org"

WORKDIR /app

# Re-install build-essential to be sure to have gcc
RUN apt update && \
    apt install --yes python3.6-dev python3.7-dev python3.8-dev build-essential && \
    pip install --no-cache-dir tox && \
    apt-get clean && \
    rm --force --recursive /var/lib/apt/lists/*
