"""create initial first tables

Revision ID: e54472b5c0b3
Revises:
Create Date: 2017-03-13 16:55:22.509970

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e54472b5c0b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authority',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='plr'
    )
    op.create_table(
        'topic',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='plr'
    )
    op.create_table(
        'plr_97',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenor', sa.String(), nullable=True),
        sa.Column('topic_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('legal_state', sa.String(), nullable=True),
        sa.Column('publication_date', sa.Date(), nullable=True),
        sa.Column('authority_id', sa.String(), nullable=False),
        sa.Column('geom', geoalchemy2.types.Geometry(
            geometry_type='MULTILINESTRING', srid=2056), nullable=True
        ),
        sa.ForeignKeyConstraint(['authority_id'], [u'plr.authority.id'], ),
        sa.ForeignKeyConstraint(['topic_id'], [u'plr.topic.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='plr'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plr_97', schema='plr')
    op.drop_table('topic', schema='plr')
    op.drop_table('authority', schema='plr')
    # ### end Alembic commands ###
